#konfigurujemy połączenie z bazą danych
spring:
  datasource:
    url: jdbc:postgresql://localhost:54329/student
    username: student
    password: student
  jpa:
    show-sql: true # ten parametr pozwala nam na wyświetlanie zapytań sql wykonanych przez naszą aplilkację w logach
    hibernate:
      ddl-auto: create-drop # ten parametr odpowiada za sposób generowania struktury bazy danych
  application:
    name: students
